### ISSUE TITLE
filter contacts by domain

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#216]
### Expected behaviour
Should filter contacts by authenticated user domain 

### Actual behaviour
Any user retrieve all CONTACTS.

### Todo
- [x] model already have domain
- [x] update contacts service to query by domain;
- [x] add firestore recommended index (will be asked when the first updated query execute)
- [x] check if create and update contacts save domain correctly

**Comment by danconte72** [comment]
- index [link](https://console.firebase.google.com/u/0/project/ion-employee/database/firestore/indexes?create_index=Eghjb250YWN0cxoKCgZkb21haW4QAhoPCgtkaXNwbGF5TmFtZRACGgwKCF9fbmFtZV9fEAI)

**Comment by danconte72** [comment]
- [ ] set contacts domain do `katrium.meumobi.com`

**Comment by danconte72** [comment]
TO ADD domain on contacts 
```js
 db.collection('contacts')
  .get()
  .then(function(querySnapshot) {
    querySnapshot.forEach(function(doc) {
      db.collection("contacts").doc(doc.id).update({"domain":'katrium.meumobi.com'});
    });
  })
  .catch(function(e) {
    console.log(e);
  });
```
